FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Instalar herramientas globales
RUN dotnet tool install --global dotnet-ef
ENV PATH="/root/.dotnet/tools:${PATH}"

# Copiar archivos del proyecto
COPY . .

# Exponer puerto
EXPOSE 8080

# Ejecutar en modo desarrollo (con restore, migraciones con retry, y watch)
CMD ["sh", "-c", "dotnet restore --no-cache && while ! dotnet ef database update --no-build; do echo 'Esperando base de datos...'; sleep 5; done && dotnet watch run --no-restore"]
